export const ROOM_STATUS = Object.freeze({
  WAITING: 'WAITING',
  DESCRIBING: 'DESCRIBING',
  CHATTING: 'CHATTING',
  VOTING: 'VOTING',
  ENDED: 'ENDED',
  DESTROYED: 'DESTROYED',
});

export const GAME_MODE = Object.freeze({
  CHAT_UNDERCOVER: 'CHAT_UNDERCOVER',
  WORD_UNDERCOVER: 'WORD_UNDERCOVER',
});

export const ROOM_EVENT = Object.freeze({
  CHAT_MESSAGE: 'CHAT_MESSAGE',
  TIMER_EXPIRED: 'TIMER_EXPIRED',
  VOTING_STARTED: 'VOTING_STARTED',
  VOTE_UPDATED: 'VOTE_UPDATED',
  PLAYER_ELIMINATED: 'PLAYER_ELIMINATED',
  ROUND_STARTED: 'ROUND_STARTED',
  WORD_DESCRIPTION_SUBMITTED: 'WORD_DESCRIPTION_SUBMITTED',
  WORD_ROUND_STARTED: 'WORD_ROUND_STARTED',
  GAME_ENDED: 'GAME_ENDED',
});

export function isGameActive(status) {
  return [ROOM_STATUS.DESCRIBING, ROOM_STATUS.CHATTING, ROOM_STATUS.VOTING, ROOM_STATUS.ENDED].includes(status);
}
